umi_gripper:
  ros__parameters:
    dxl.port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT6RW7D6-if00-port0
    dxl.baud: 57600
    dxl.gripper_id: 0
    trigger.min_tick: 590
    trigger.max_tick: 2500
    gripper.min_tick: -653
    gripper.max_tick: 733
    gripper.invert: true
    dxl.cmd_rate_hz: 30.0
    dxl.pos_deadband: 2
    dxl.pos_slew_per_sec: 1000.0
    dxl.profile_accel: 0
    dxl.profile_velocity: 0
    dxl.current_limit_mA: 1345
    dxl.goal_current_mA: 500
    dxl.goal_current_min_mA: 0
    dxl.goal_current_max_mA: 1345
    gripper.current_stop_enabled: true
    gripper.close_current_stop_mA: 400
    gripper.current_stop_debounce_sec: 0.12
    monitor.enabled: true
    monitor.print_period_sec: 0.5
    gripper.present_current_mA_topic: /gripper/present_current_mA
    gripper.present_position_topic: /gripper/present_position
    gripper.command_topic: /gripper/command
    gripper.goal_current_mA_topic: /gripper/goal_current_mA
    keyboard.step_size: 50
