umi_gripper_sub:
  ros__parameters:
    dxl.port: /dev/ttyUSB0
    dxl.baud: 57600
    dxl.gripper_id: 0
    gripper.min_tick: 590
    gripper.max_tick: 2500
    dxl.cmd_rate_hz: 50.0
    dxl.pos_deadband: 2
    dxl.pos_slew_per_sec: 2000.0
    dxl.profile_accel: 0
    dxl.profile_velocity: 0
    dxl.current_limit_mA: 1345
    dxl.goal_current_mA: 200
    gripper.current_stop_enabled: true
    gripper.close_current_stop_mA: 400
    gripper.close_increases_tick: true
    gripper.present_current_mA_topic: /gripper/present_current_mA
    gripper.present_position_topic: /gripper/present_position
    gripper.command_topic: /gripper/command
    joystick.enabled: true
    joystick.command_topic: /ur10skku/joy_move
    joystick.axis_index: 5
