f710_gripper_joy_controller:
  ros__parameters:
    joy_topic: /joy_f710
    command_topic: /gripper/command
    present_position_topic: /gripper/present_position
    use_present_position: true

    min_tick: 590
    max_tick: 2500
    home_tick: -1
    initial_tick: -1
    step_tick: 50

    button_open: 4
    button_close: 5
    button_home: 0
    button_enable: -1
    button_debounce_sec: 0.20

    dpad_axis: 6
    dpad_threshold: 0.50
    dpad_invert: false
    dpad_debounce_sec: 0.15

    axis_control.enabled: false
    axis_control.axis_index: 5
    axis_control.released_value: 1.0
    axis_control.pressed_value: -1.0
    axis_control.activation_threshold: 0.05
    axis_control.min_change_tick: 5
    axis_control.publish_rate_hz: 30.0
    axis_control.enable_button: -1

    log_commands: true
