#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
demo_data_imitation_form.py

Convert multimodal merged demonstration HDF5 into per-episode imitation-learning
HDF5 files for nrs_imitation.

This converter matches the recorder layout generated by:

  vr_demo_hdf5_recorder.py  (multimodal version)

Expected merged HDF5 layout:

  merged.hdf5
  └── episodes/
      ├── ep_0000/
      │   ├── position                  (T, 6)
      │   ├── ft                        (T, 3)
      │   ├── images/
      │   │   ├── cam0                  (T, H, W, 3)
      │   │   └── cam1                  (T, H, W, 3) optional/global cam
      │   ├── marker/
      │   │   ├── id0                   (T, 7) [x,y,z,rx,ry,rz,valid]
      │   │   ├── id1                   (T, 7) [x,y,z,rx,ry,rz,valid]
      │   │   ├── combined              (T,14)
      │   │   ├── id0_quat              (T, 8) optional
      │   │   └── id1_quat              (T, 8) optional
      │   ├── gripper/
      │   │   ├── present_position      (T,)
      │   │   └── present_current_mA    (T,)
      │   └── marker                    (T,14) optional top-level alias
      └── ep_0001/
          └── ...

Output per-episode HDF5 layout:

  episode_0.hdf5
  ├── action/
  │   ├── position                      (T_out, 6)
  │   ├── force                         (T_out, 3)
  │   └── gripper_present_position      (T_out,)
  ├── observations/
  │   ├── position                      (T_out, 6)
  │   ├── force                         (T_out, 3)
  │   ├── marker                        (T_out,14) [id0(7), id1(7)]
  │   ├── marker_id0                    (T_out, 7)
  │   ├── marker_id1                    (T_out, 7)
  │   ├── marker_id0_quat               (T_out, 8), if available
  │   ├── marker_id1_quat               (T_out, 8), if available
  │   ├── gripper/
  │   │   ├── present_position          (T_out,)
  │   │   └── present_current_mA        (T_out,)
  │   ├── images/
  │   │   ├── cam0                      (T_out,H,W,3)
  │   │   └── cam1                      (T_out,H,W,3)
  │   └── is_pad                        (T_out,)
  └── meta/
      attrs:
        orig_len, T_pad, pad_starts_at, truncated, camera_names_json, marker_dim

Core observation for training:

  qpos   = position(6) + force(3)
  image  = cam0 or cam0+cam1 depending on obs_mode
  marker = marker id0 + id1 = (T,14)

Marker convention:
  id0 = robot EE marker or VR tracker top marker
  id1 = workpiece/surface marker
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import shutil
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import h5py
import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[2]
ACT_ROOT_DEFAULT = str(PROJECT_ROOT / "datasets" / "ACT")


# ============================================================
# Path helpers
# ============================================================

def find_latest_merged_h5(act_root: str) -> str:
    patterns = [
        os.path.join(act_root, "*", "merged_hdf5", "*.hdf5"),
        os.path.join(act_root, "*", "merged_hdf5", "*.h5"),
    ]
    files: List[str] = []
    for p in patterns:
        files.extend(glob.glob(p))
    files = sorted(set(files))
    if not files:
        raise FileNotFoundError(
            f"No merged HDF5 found under {act_root}/*/merged_hdf5/*.hdf5"
        )
    return files[-1]


def infer_output_dir_from_input(input_h5: str, output_name: str) -> str:
    p = Path(input_h5).resolve()
    # .../datasets/ACT/YYYYMMDD_HHMM/merged_hdf5/file.hdf5
    if p.parent.name == "merged_hdf5":
        return str(p.parent.parent / output_name)
    return str(p.parent / output_name)


def ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)


# ============================================================
# HDF5 read helpers
# ============================================================

def _has_path(g: h5py.Group, path: str) -> bool:
    try:
        _ = g[path]
        return True
    except Exception:
        return False


def _read_array(g: h5py.Group, path: str, dtype=None):
    if not _has_path(g, path):
        raise KeyError(f"Missing required dataset: {g.name}/{path}")
    arr = np.asarray(g[path])
    if dtype is not None:
        arr = arr.astype(dtype)
    return arr


def _read_optional_array(g: h5py.Group, path: str, dtype=None):
    if not _has_path(g, path):
        return None
    arr = np.asarray(g[path])
    if dtype is not None:
        arr = arr.astype(dtype)
    return arr


def _first_existing_array(g: h5py.Group, paths: List[str], dtype=None):
    for p in paths:
        arr = _read_optional_array(g, p, dtype=dtype)
        if arr is not None:
            return arr, p
    return None, ""


def _ensure_2d(arr: np.ndarray, dim: int, name: str) -> np.ndarray:
    arr = np.asarray(arr)
    if arr.ndim == 1 and arr.size == dim:
        arr = arr.reshape(1, dim)
    if arr.ndim != 2 or arr.shape[1] != dim:
        raise ValueError(f"{name} must be (T,{dim}), got {arr.shape}")
    return arr


def _ensure_image4(arr: np.ndarray, name: str) -> np.ndarray:
    arr = np.asarray(arr)
    if arr.ndim != 4 or arr.shape[-1] != 3:
        raise ValueError(f"{name} must be (T,H,W,3), got {arr.shape}")
    if arr.dtype != np.uint8:
        # Clip instead of failing. Some recorders may save float RGB.
        arr = np.clip(arr, 0, 255).astype(np.uint8)
    return arr


def _ensure_vector1(arr: np.ndarray, name: str) -> np.ndarray:
    arr = np.asarray(arr)
    if arr.ndim == 0:
        arr = arr.reshape(1)
    if arr.ndim == 2 and arr.shape[1] == 1:
        arr = arr[:, 0]
    if arr.ndim != 1:
        raise ValueError(f"{name} must be (T,) or (T,1), got {arr.shape}")
    return arr


def _trim_to_min_len(items: Dict[str, np.ndarray]) -> Tuple[Dict[str, np.ndarray], int]:
    lengths = []
    for k, v in items.items():
        if v is not None:
            lengths.append(int(v.shape[0]))
    if not lengths:
        raise ValueError("No arrays to trim.")
    T = min(lengths)
    out = {}
    for k, v in items.items():
        if v is None:
            out[k] = None
        else:
            out[k] = v[:T]
    return out, T


# ============================================================
# Marker helpers
# ============================================================

def make_zero_marker(T: int, dim: int = 7) -> np.ndarray:
    return np.zeros((int(T), int(dim)), dtype=np.float32)


def normalize_marker7(marker: Optional[np.ndarray], T: int, name: str) -> np.ndarray:
    """
    Return (T,7) marker.
    Accepted:
      - None -> zeros
      - (T,7) [x,y,z,rx,ry,rz,valid]
      - (T,6) [x,y,z,rx,ry,rz], valid=1
      - (T,8) [x,y,z,qx,qy,qz,qw,valid] is NOT converted here.
    """
    if marker is None:
        return make_zero_marker(T, 7)

    marker = np.asarray(marker, dtype=np.float32)
    if marker.ndim != 2:
        raise ValueError(f"{name} marker must be 2D, got {marker.shape}")

    marker = marker[:T]

    if marker.shape[1] == 7:
        return marker.astype(np.float32)

    if marker.shape[1] == 6:
        valid = np.ones((marker.shape[0], 1), dtype=np.float32)
        return np.concatenate([marker, valid], axis=1).astype(np.float32)

    raise ValueError(
        f"{name} marker must have dim 6 or 7. "
        f"Expected rotvec marker [x,y,z,rx,ry,rz,(valid)], got {marker.shape}"
    )


def normalize_marker8_quat(marker: Optional[np.ndarray], T: int) -> Optional[np.ndarray]:
    """
    Return optional (T,8) quat marker.
    Accepted:
      - None -> None
      - (T,8) [x,y,z,qx,qy,qz,qw,valid]
      - (T,7) [x,y,z,qx,qy,qz,qw], valid=1
    """
    if marker is None:
        return None
    marker = np.asarray(marker, dtype=np.float32)
    if marker.ndim != 2:
        return None
    marker = marker[:T]

    if marker.shape[1] == 8:
        return marker.astype(np.float32)
    if marker.shape[1] == 7:
        valid = np.ones((marker.shape[0], 1), dtype=np.float32)
        return np.concatenate([marker, valid], axis=1).astype(np.float32)
    return None


def load_marker_pair(g_ep: h5py.Group, T: int, require_marker: bool) -> Tuple[np.ndarray, np.ndarray, np.ndarray, Optional[np.ndarray], Optional[np.ndarray], Dict[str, str]]:
    """
    Load id0/id1 marker and combined marker from an input episode group.
    """
    source_paths: Dict[str, str] = {}

    # Preferred recorder paths.
    id0, p0 = _first_existing_array(
        g_ep,
        [
            "marker/id0",
            "observations/marker_id0",
            "observations/marker/id0",
            "aruco/id0",
            "aruco/id_0",
        ],
        dtype=np.float32,
    )
    id1, p1 = _first_existing_array(
        g_ep,
        [
            "marker/id1",
            "observations/marker_id1",
            "observations/marker/id1",
            "aruco/id1",
            "aruco/id_1",
        ],
        dtype=np.float32,
    )

    combined, pc = _first_existing_array(
        g_ep,
        [
            "marker/combined",
            "marker",
            "observations/marker",
            "aruco/combined",
        ],
        dtype=np.float32,
    )

    if combined is not None and combined.ndim == 2 and combined.shape[1] >= 14:
        combined = combined[:T, :14].astype(np.float32)
        if id0 is None:
            id0 = combined[:, :7]
            p0 = pc + "[:, :7]"
        if id1 is None:
            id1 = combined[:, 7:14]
            p1 = pc + "[:, 7:14]"

    if require_marker and (id0 is None or id1 is None):
        raise KeyError(
            f"require_marker=True but marker id0/id1 not found in {g_ep.name}. "
            f"Found paths: id0={p0}, id1={p1}, combined={pc}"
        )

    id0 = normalize_marker7(id0, T, "id0")
    id1 = normalize_marker7(id1, T, "id1")
    combined = np.concatenate([id0, id1], axis=1).astype(np.float32)

    id0q, p0q = _first_existing_array(
        g_ep,
        [
            "marker/id0_quat",
            "observations/marker_id0_quat",
            "aruco/id0_quat",
        ],
        dtype=np.float32,
    )
    id1q, p1q = _first_existing_array(
        g_ep,
        [
            "marker/id1_quat",
            "observations/marker_id1_quat",
            "aruco/id1_quat",
        ],
        dtype=np.float32,
    )

    id0q = normalize_marker8_quat(id0q, T)
    id1q = normalize_marker8_quat(id1q, T)

    source_paths["marker_id0"] = p0
    source_paths["marker_id1"] = p1
    source_paths["marker_combined"] = pc
    source_paths["marker_id0_quat"] = p0q
    source_paths["marker_id1_quat"] = p1q

    return id0, id1, combined, id0q, id1q, source_paths


# ============================================================
# Episode conversion
# ============================================================

def load_input_episode(
    g_ep: h5py.Group,
    require_cam1: bool,
    require_marker: bool,
) -> Dict[str, np.ndarray]:
    """
    Load one input episode group into normalized arrays.
    """
    # Required core.
    position, position_path = _first_existing_array(
        g_ep,
        [
            "position",
            "observations/position",
        ],
        dtype=np.float32,
    )
    if position is None:
        raise KeyError(f"Missing position in {g_ep.name}")

    force, force_path = _first_existing_array(
        g_ep,
        [
            "ft",
            "force",
            "observations/force",
        ],
        dtype=np.float32,
    )
    if force is None:
        raise KeyError(f"Missing force/ft in {g_ep.name}")

    cam0, cam0_path = _first_existing_array(
        g_ep,
        [
            "images/cam0",
            "observations/images/cam0",
            "image",
            "images/rgb",
        ],
        dtype=None,
    )
    if cam0 is None:
        raise KeyError(f"Missing cam0 image in {g_ep.name}")

    cam1, cam1_path = _first_existing_array(
        g_ep,
        [
            "images/cam1",
            "images/global",
            "observations/images/cam1",
            "observations/images/global",
        ],
        dtype=None,
    )
    if require_cam1 and cam1 is None:
        raise KeyError(f"require_cam1=True but cam1/global image missing in {g_ep.name}")

    gripper_position, gripper_position_path = _first_existing_array(
        g_ep,
        [
            "gripper/present_position",
            "observations/gripper/present_position",
        ],
        dtype=np.int32,
    )
    if gripper_position is None:
        raise KeyError(f"Missing gripper present_position in {g_ep.name}")

    gripper_current_mA, gripper_current_path = _first_existing_array(
        g_ep,
        [
            "gripper/present_current_mA",
            "observations/gripper/present_current_mA",
        ],
        dtype=np.float32,
    )
    if gripper_current_mA is None:
        raise KeyError(f"Missing gripper present_current_mA in {g_ep.name}")

    position = _ensure_2d(position, 6, "position").astype(np.float32)
    force = _ensure_2d(force[:, :3], 3, "force").astype(np.float32)
    cam0 = _ensure_image4(cam0, "cam0")
    gripper_position = _ensure_vector1(gripper_position, "gripper present_position").astype(np.int32)
    gripper_current_mA = _ensure_vector1(gripper_current_mA, "gripper present_current_mA").astype(np.float32)

    if cam1 is not None:
        cam1 = _ensure_image4(cam1, "cam1")
    else:
        # If missing and not required, create a zero cam1 with same shape as cam0.
        cam1 = np.zeros_like(cam0, dtype=np.uint8)
        cam1_path = "ZERO_FILLED"

    # Trim all core streams first.
    core, T = _trim_to_min_len(
        {
            "position": position,
            "force": force,
            "cam0": cam0,
            "cam1": cam1,
            "gripper_position": gripper_position,
            "gripper_current_mA": gripper_current_mA,
        }
    )
    position = core["position"]
    force = core["force"]
    cam0 = core["cam0"]
    cam1 = core["cam1"]
    gripper_position = core["gripper_position"]
    gripper_current_mA = core["gripper_current_mA"]

    id0, id1, marker, id0q, id1q, marker_paths = load_marker_pair(
        g_ep,
        T=T,
        require_marker=require_marker,
    )

    source_paths = {
        "position": position_path,
        "force": force_path,
        "cam0": cam0_path,
        "cam1": cam1_path,
        "gripper_position": gripper_position_path,
        "gripper_current_mA": gripper_current_path,
    }
    source_paths.update(marker_paths)

    return {
        "position": position.astype(np.float32),
        "force": force.astype(np.float32),
        "cam0": cam0.astype(np.uint8),
        "cam1": cam1.astype(np.uint8),
        "gripper_present_position": gripper_position.astype(np.int32),
        "gripper_present_current_mA": gripper_current_mA.astype(np.float32),
        "marker_id0": id0.astype(np.float32),
        "marker_id1": id1.astype(np.float32),
        "marker": marker.astype(np.float32),
        "marker_id0_quat": id0q,
        "marker_id1_quat": id1q,
        "source_paths_json": json.dumps(source_paths, ensure_ascii=False),
    }


def truncate_episode(data: Dict[str, np.ndarray], max_len: int) -> Tuple[Dict[str, np.ndarray], bool, int]:
    if max_len <= 0:
        T = int(data["position"].shape[0])
        return data, False, T

    T = int(data["position"].shape[0])
    if T <= max_len:
        return data, False, T

    out = {}
    for k, v in data.items():
        if isinstance(v, np.ndarray) and v.shape[0] == T:
            out[k] = v[:max_len]
        else:
            out[k] = v
    return out, True, max_len


def write_output_episode(
    out_path: str,
    data: Dict[str, np.ndarray],
    ep_name: str,
    source_h5: str,
    source_paths_json: str,
    camera_names: List[str],
    compression: str,
    gzip_level: int,
    truncated: bool,
    orig_len: int,
):
    T = int(data["position"].shape[0])
    is_pad = np.zeros((T,), dtype=bool)

    if os.path.exists(out_path):
        os.remove(out_path)

    img_kwargs = {}
    arr_kwargs = {}
    if compression == "gzip":
        img_kwargs = dict(compression="gzip", compression_opts=int(gzip_level), shuffle=True)
        arr_kwargs = dict(compression="gzip", compression_opts=int(gzip_level), shuffle=True)
    elif compression == "lzf":
        img_kwargs = dict(compression="lzf", shuffle=True)
        arr_kwargs = dict(compression="lzf", shuffle=True)

    with h5py.File(out_path, "w") as f:
        f.attrs["schema_version"] = "episode_multimodal_v2"
        f.attrs["source_h5"] = str(source_h5)
        f.attrs["source_episode"] = str(ep_name)
        f.attrs["camera_names_json"] = json.dumps(camera_names)
        f.attrs["marker_format"] = "[id0: x,y,z,rx,ry,rz,valid] + [id1: x,y,z,rx,ry,rz,valid]"
        f.attrs["marker_dim"] = int(data["marker"].shape[1])
        f.attrs["qpos_dim"] = 9
        f.attrs["action_dim"] = 10

        g_action = f.create_group("action")
        g_action.create_dataset("position", data=data["position"].astype(np.float32), **arr_kwargs)
        g_action.create_dataset("force", data=data["force"].astype(np.float32), **arr_kwargs)
        g_action.create_dataset("gripper_present_position", data=data["gripper_present_position"].astype(np.int32), **arr_kwargs)

        g_obs = f.create_group("observations")
        g_obs.create_dataset("position", data=data["position"].astype(np.float32), **arr_kwargs)
        g_obs.create_dataset("force", data=data["force"].astype(np.float32), **arr_kwargs)
        g_obs.create_dataset("marker", data=data["marker"].astype(np.float32), **arr_kwargs)
        g_obs.create_dataset("marker_id0", data=data["marker_id0"].astype(np.float32), **arr_kwargs)
        g_obs.create_dataset("marker_id1", data=data["marker_id1"].astype(np.float32), **arr_kwargs)

        if data.get("marker_id0_quat") is not None:
            g_obs.create_dataset("marker_id0_quat", data=data["marker_id0_quat"].astype(np.float32), **arr_kwargs)
        if data.get("marker_id1_quat") is not None:
            g_obs.create_dataset("marker_id1_quat", data=data["marker_id1_quat"].astype(np.float32), **arr_kwargs)

        g_gripper = g_obs.create_group("gripper")
        g_gripper.create_dataset("present_position", data=data["gripper_present_position"].astype(np.int32), **arr_kwargs)
        g_gripper.create_dataset("present_current_mA", data=data["gripper_present_current_mA"].astype(np.float32), **arr_kwargs)

        g_img = g_obs.create_group("images")
        g_img.create_dataset("cam0", data=data["cam0"].astype(np.uint8), **img_kwargs)
        g_img.create_dataset("cam1", data=data["cam1"].astype(np.uint8), **img_kwargs)

        g_obs.create_dataset("is_pad", data=is_pad)

        g_meta = f.create_group("meta")
        g_meta.attrs["orig_len"] = int(orig_len)
        g_meta.attrs["T_pad"] = int(T)
        g_meta.attrs["pad_starts_at"] = int(T)
        g_meta.attrs["truncated"] = int(bool(truncated))
        g_meta.attrs["camera_names_json"] = json.dumps(camera_names)
        g_meta.attrs["source_paths_json"] = source_paths_json
        g_meta.attrs["source_h5"] = str(source_h5)
        g_meta.attrs["source_episode"] = str(ep_name)
        g_meta.attrs["marker_dim"] = int(data["marker"].shape[1])
        g_meta.attrs["gripper_position_dtype"] = "int32"
        g_meta.attrs["gripper_current_dtype"] = "float32"

        # Compatibility aliases for older quick inspection scripts. The flat
        # action alias cannot be named "action" because /action is the
        # canonical group containing position and force datasets.
        f.create_dataset("qpos", data=np.concatenate([data["position"], data["force"]], axis=1).astype(np.float32), **arr_kwargs)
        f.create_dataset(
            "action_flat",
            data=np.concatenate(
                [
                    data["position"],
                    data["force"],
                    data["gripper_present_position"].reshape(-1, 1).astype(np.float32),
                ],
                axis=1,
            ).astype(np.float32),
            **arr_kwargs,
        )


def convert_merged_h5(
    input_h5: str,
    output_dir: str,
    require_cam1: bool,
    require_marker: bool,
    min_len: int,
    max_len: int,
    compression: str,
    gzip_level: int,
    overwrite: bool,
    keep_failed: bool = False,
) -> List[str]:
    input_h5 = str(Path(input_h5).expanduser().resolve())
    output_dir = str(Path(output_dir).expanduser().resolve())

    if not os.path.exists(input_h5):
        raise FileNotFoundError(input_h5)

    if os.path.exists(output_dir):
        if overwrite:
            shutil.rmtree(output_dir)
        else:
            existing = sorted(glob.glob(os.path.join(output_dir, "episode_*.hdf5")))
            if existing:
                raise RuntimeError(
                    f"Output dir already contains episode files: {output_dir}. "
                    f"Use --overwrite to replace."
                )

    ensure_dir(output_dir)

    written: List[str] = []
    failed: List[Tuple[str, str]] = []

    with h5py.File(input_h5, "r") as f:
        if "episodes" not in f:
            raise KeyError(f"{input_h5} does not contain /episodes group")

        ep_names = sorted(list(f["episodes"].keys()))
        if not ep_names:
            raise RuntimeError(f"No episodes found in {input_h5}/episodes")

        print(f"[INFO] input_h5       = {input_h5}")
        print(f"[INFO] output_dir     = {output_dir}")
        print(f"[INFO] episodes found = {len(ep_names)}")
        print(f"[INFO] require_cam1   = {require_cam1}")
        print(f"[INFO] require_marker = {require_marker}")

        out_idx = 0
        for ep_name in ep_names:
            g_ep = f["episodes"][ep_name]

            try:
                data = load_input_episode(
                    g_ep,
                    require_cam1=bool(require_cam1),
                    require_marker=bool(require_marker),
                )

                orig_len = int(data["position"].shape[0])
                if orig_len < int(min_len):
                    raise RuntimeError(f"too short: T={orig_len} < min_len={min_len}")

                data, truncated, T_out = truncate_episode(data, max_len=max_len)

                camera_names = ["cam0", "cam1"]
                out_path = os.path.join(output_dir, f"episode_{out_idx}.hdf5")

                write_output_episode(
                    out_path=out_path,
                    data=data,
                    ep_name=ep_name,
                    source_h5=input_h5,
                    source_paths_json=str(data.get("source_paths_json", "{}")),
                    camera_names=camera_names,
                    compression=compression,
                    gzip_level=gzip_level,
                    truncated=truncated,
                    orig_len=orig_len,
                )

                m0_valid = int(np.sum(data["marker_id0"][:, -1] > 0.5))
                m1_valid = int(np.sum(data["marker_id1"][:, -1] > 0.5))

                print(
                    f"[OK] {ep_name} -> episode_{out_idx}.hdf5 | "
                    f"T={T_out}, cam0={data['cam0'].shape}, cam1={data['cam1'].shape}, "
                    f"marker={data['marker'].shape}, id0_valid={m0_valid}/{T_out}, id1_valid={m1_valid}/{T_out}, "
                    f"gripper_position={data['gripper_present_position'].shape}, "
                    f"gripper_current_mA={data['gripper_present_current_mA'].shape}"
                )

                written.append(out_path)
                out_idx += 1

            except Exception as e:
                msg = f"{type(e).__name__}: {e}"
                failed.append((ep_name, msg))
                print(f"[FAIL] {ep_name}: {msg}")
                if not keep_failed:
                    continue

    summary_path = os.path.join(output_dir, "conversion_summary.json")
    summary = {
        "input_h5": input_h5,
        "output_dir": output_dir,
        "num_written": len(written),
        "written": written,
        "num_failed": len(failed),
        "failed": [{"episode": ep, "error": err} for ep, err in failed],
        "require_cam1": bool(require_cam1),
        "require_marker": bool(require_marker),
        "schema_version": "episode_multimodal_v2",
    }
    with open(summary_path, "w", encoding="utf-8") as fp:
        json.dump(summary, fp, indent=2, ensure_ascii=False)

    print(f"[INFO] wrote summary: {summary_path}")
    print(f"[DONE] converted episodes: {len(written)} / {len(written) + len(failed)}")

    if not written:
        raise RuntimeError("No episodes were converted successfully.")

    return written


# ============================================================
# CLI
# ============================================================

def parse_args():
    parser = argparse.ArgumentParser(
        description="Convert multimodal merged HDF5 to per-episode imitation HDF5."
    )

    parser.add_argument(
        "--input_h5",
        type=str,
        default="",
        help="Path to merged HDF5. If empty, use latest under --act_root.",
    )
    parser.add_argument(
        "--act_root",
        type=str,
        default=ACT_ROOT_DEFAULT,
        help="Root used for auto-latest merged HDF5 search.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="",
        help="Output directory. If empty, inferred as <dataset_time>/episodes_multimodal.",
    )
    parser.add_argument(
        "--output_name",
        type=str,
        default="episodes_multimodal",
        help="Output folder name when --output_dir is empty.",
    )

    parser.add_argument("--require_cam1", action="store_true", help="Fail episode if cam1/global image is missing.")
    parser.add_argument("--require_marker", action="store_true", help="Fail episode if marker id0/id1 is missing.")

    parser.add_argument("--min_len", type=int, default=10)
    parser.add_argument("--max_len", type=int, default=0, help="0 means no truncation.")

    parser.add_argument("--compression", type=str, default="gzip", choices=["gzip", "lzf", "none"])
    parser.add_argument("--gzip_level", type=int, default=4)

    parser.add_argument("--overwrite", action="store_true", help="Overwrite output dir if it exists.")
    parser.add_argument("--keep_failed", action="store_true", help="Continue conversion and keep summary of failures.")

    return parser.parse_args()


def main():
    args = parse_args()

    input_h5 = args.input_h5.strip()
    if not input_h5:
        input_h5 = find_latest_merged_h5(args.act_root)

    output_dir = args.output_dir.strip()
    if not output_dir:
        output_dir = infer_output_dir_from_input(input_h5, args.output_name)

    compression = str(args.compression).lower()
    if compression == "none":
        compression = "none"

    convert_merged_h5(
        input_h5=input_h5,
        output_dir=output_dir,
        require_cam1=bool(args.require_cam1),
        require_marker=bool(args.require_marker),
        min_len=int(args.min_len),
        max_len=int(args.max_len),
        compression=compression,
        gzip_level=int(args.gzip_level),
        overwrite=bool(args.overwrite),
        keep_failed=bool(args.keep_failed),
    )


if __name__ == "__main__":
    main()
